### ISSUE TITLE
Filter out rogue HTML from messages

### ISSUE THREAD

**Issue by Half-Shot** [Half-Shot/matrix-appservice-discord#163] opened 2018-06-11 16:48 UTC
@tulir has created pretty rainbox text using ``<font>`` and in the process made discord look super ugly.

**Comment by Sorunome** [comment] 2018-07-20 10:35
I think that the issue is that, in the normal `body` attribute that html is, not only in `formatted_body` when sending stuff.

**Comment by Half-Shot** [comment] 2018-07-20 13:22
Yes, that certainly doesn't help.

**Comment by Sorunome** [comment] 2018-12-21 17:03
merged

**Closed by Sorunome** 2018-12-21 17:03 UTC
Labels: bug
