### ISSUE TITLE
Redacting an already-redacted message causes another message to be deleted

### ISSUE THREAD

**Issue by auscompgeek** [Half-Shot/matrix-appservice-discord#539] opened 2019-07-29 08:05 UTC
Described in https://github.com/matrix-org/matrix-appservice-slack/issues/173#issuecomment-514634204

When an `m.room.redaction` event comes in, redacting message A that has already been redacted, after message B was sent, message B is deleted on Discord, which then gets echoed back to Matrix.

**Comment by Sorunome** [comment] 2019-08-13 16:09
duplicate of #422

**Closed by Sorunome** 2019-08-13 16:09 UTC
