### ISSUE TITLE
Reacji support

### ISSUE THREAD

**Issue by tgr** [Half-Shot/matrix-appservice-discord#759] opened 2021-12-29 05:56 UTC
Reacjis (emoji responses) are not supported in either direction. These days it's common to use them for more than just flourish (voting, indicating agreement, simple status management etc.) so it would be great if that were fixed

**Comment by tgr** [comment] 2021-12-29 05:57
See also #700.

**Comment by auscompgeek** [comment] 2021-12-29 06:45
Duplicate of #468 and #469.

**Closed as completed** 2021-12-29 07:07 UTC
