### ISSUE TITLE
New Discord replies aren't mirrored to Matrix

### ISSUE THREAD

**Issue by igeljaeger** [Half-Shot/matrix-appservice-discord#706] opened 2021-05-25 20:30 UTC
Discord implemented a new reply system a year ago or so which does not mirror to matrix at all. It used to be a manual quote but this changed and now only works from Matrix to Discord but not the other way around.

**Comment by jackmawer** [comment] 2021-06-06 12:46
This might be a duplicate of #631, and is related to #693.

**Comment by BBaoVanC** [comment] 2021-07-04 03:15
This would be solved by #704

**Comment by rollingmoai** [comment] 2022-09-03 04:16
This should be closed as a duplicate of #631.

**Closed as completed** 2024-09-22 22:43 UTC
Labels: T-Defect
