### ISSUE TITLE
Automatic webhook creation doesn't work

### ISSUE THREAD

**Issue by turt2live** [Half-Shot/matrix-appservice-discord#84] opened 2018-02-18 04:27 UTC
There's a cutoff error in my logs that starts with "The system could not find the file specified" as an unhandled promise rejection. That's unfortunately all I can find :(

Steps run (may or may not reproduce the issue):
1. Use an old version of the bridge (~20 commits ago on develop)
2. Bridge a guild
3. Upgrade the bridge to the current develop (as of reporting this)
4. Create a new channel in your guild
5. Join the portal room for that channel
6. Send messages from matrix

**Comment by Half-Shot** [comment] 2018-02-19 14:50
Oh I think I see why. The webhook code tries to find a image with the path of `""`. The problem is for a description to work, we must also pass an image due to arg positioning :/

**Comment by Half-Shot** [comment] 2018-02-20 17:52
Travis seems to be happy that it's fixed with some package bumps.

**Closed by Half-Shot** 2018-02-20 17:52 UTC
Labels: bug

**Comment by turt2live** [comment] 2018-02-20 18:06
Not sure if you mean me or travis-ci, but both are happy :)
