### ISSUE TITLE
Quote escaped by the IRC bridge are not sent correctly to discord

### ISSUE THREAD

**Issue by erdnaxeli** [Half-Shot/matrix-appservice-discord#730] opened 2021-09-14 09:02 UTC
Hi,

Here is a message sent from a user using the matrix-appservice-irc bridge:
```
{
  "content": {
    "body": "Le bridge n'avait pas ce problème avant le restart de la semaine dernière si jamais ça peut aider :shrug:",
    "format": "org.matrix.custom.html",
    "formatted_body": "Le bridge n&apos;avait pas ce problème avant le restart de la semaine dernière si jamais ça peut aider :shrug:",
    "msgtype": "m.text"
  },
  "event_id": "...",
  "origin_server_ts": 1631540156568,
  "room_id": "...",
  "sender": "...",
  "type": "m.room.message",
  "unsigned": {
    "age": 69466870
  },
  "user_id": "...",
  "age": 69466870
}
```

We can see that the formatted body contains `&apos;`. This is sent as is to discord, which is not expected. I would expect to see a quote `'` in the discord message.

I read the spec about [org.matrix.custom.html](https://matrix.org/docs/spec/client_server/r0.6.1#m-room-message-msgtypes), but it says nothing about escaping quotes. As this is valid HTML, I think it is the discord bridge job to handle it correctly.

**Comment by pacien** [comment] 2021-12-04 19:24
Probably related to issue #598.

**Comment by jaller94** [comment] 2022-05-20 10:01
Closing as a duplicate of https://github.com/matrix-org/matrix-appservice-discord/issues/598

**Closed as not planned by jaller94** 2022-05-20 10:01 UTC
Labels: T-Defect
